### ISSUE TITLE
Failed to Connect to Codespaces (no error presented to user)

### ISSUE THREAD

**Issue by trevrobwhite** [github/codespaces-jetbrains-feedback#37] opened 2022-11-22 12:27 UTC
```
2022-11-22 12:15:37,955 [1638540]   INFO - #c.i.o.p.u.AbstractProgressIndicatorBase - This progress indicator (Downloading JetBrains Client 1906423223: running=true; canceled=false; task=com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$createBackgroundable$1$1@420d1521) is indeterminate, this may lead to visual inconsistency. Please call setIndeterminate(false) before you start progress. class com.intellij.openapi.progress.impl.BackgroundableProcessIndicator
java.lang.IllegalStateException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.setFraction(AbstractProgressIndicatorBase.java:196)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.setFraction(AbstractProgressIndicatorExBase.java:124)
	at com.intellij.openapi.progress.util.ProgressWindow.setFraction(ProgressWindow.java:315)
	at com.intellij.ide.util.DelegatingProgressIndicator.setFraction(DelegatingProgressIndicator.java:84)
	at com.intellij.remoteDev.util.SubProgressIndicator.setFraction(SubProgressIndicator.kt:28)
	at com.intellij.remoteDev.downloader.CodeWithMeClientDownloader$MultipleSubProgressIndicator$Companion$create$element$1.invoke(CodeWithMeClientDownloader.kt:792)
	at com.intellij.remoteDev.downloader.CodeWithMeClientDownloader$MultipleSubProgressIndicator$Companion$create$element$1.invoke(CodeWithMeClientDownloader.kt:784)
	at com.intellij.remoteDev.downloader.CodeWithMeClientDownloader$MultipleSubProgressIndicator.setFraction(CodeWithMeClientDownloader.kt:805)
	at com.intellij.remoteDev.downloader.CodeWithMeClientDownloader$downloadClientAndJdk$5.run(CodeWithMeClientDownloader.kt:323)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-11-22 12:15:38,220 [1638805]   INFO - #c.j.g.s.GoHighLevelHostAccessor - Go worker command: create-dir --path=/home/vscode/.cache/JetBrains/RemoteDev/dist/20bc096c101b6_PhpStorm-223.7571.15
Exit code: 0
2022-11-22 12:16:54,647 [1715232]   INFO - #c.i.o.p.u.AbstractProgressIndicatorBase - This progress indicator ( 1193574152: running=true; canceled=false) is indeterminate, this may lead to visual inconsistency. Please call setIndeterminate(false) before you start progress. class com.intellij.openapi.progress.util.ProgressWindow
java.lang.IllegalStateException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.setFraction(AbstractProgressIndicatorBase.java:196)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.setFraction(AbstractProgressIndicatorExBase.java:124)
	at com.intellij.openapi.progress.util.ProgressWindow.setFraction(ProgressWindow.java:315)
	at com.jetbrains.gateway.ssh.deploy.methods.DeployMethods.deployHostToRemote(DeployMethods.kt:80)
	at com.jetbrains.gateway.ssh.deploy.methods.DeployMethods$deployHostToRemote$1.invokeSuspend(DeployMethods.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1$2.invokeSuspend(BackgroundProgressCoroutineUtil.kt:159)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1.invoke(BackgroundProgressCoroutineUtil.kt:157)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1.invoke(BackgroundProgressCoroutineUtil.kt:136)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$createModal$1$1.run(BackgroundProgressCoroutineUtil.kt:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:526)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

2022-11-22 12:17:40,783 [1761368]   INFO - #c.i.o.p.u.AbstractProgressIndicatorBase - This progress indicator (Launching client 1749939817: running=true; canceled=false; task=com.intellij.remoteDev.downloader.CodeWithMeGuestLauncher$downloadCompatibleClientAndLaunch$2@597e2cc3) is indeterminate, this may lead to visual inconsistency. Please call setIndeterminate(false) before you start progress. class com.intellij.openapi.progress.impl.BackgroundableProcessIndicator
java.lang.IllegalStateException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.setFraction(AbstractProgressIndicatorBase.java:196)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.setFraction(AbstractProgressIndicatorExBase.java:124)
	at com.intellij.openapi.progress.util.ProgressWindow.setFraction(ProgressWindow.java:315)
	at com.intellij.remoteDev.downloader.CodeWithMeClientDownloader$MultipleSubProgressIndicator$Companion$create$element$1.invoke(CodeWithMeClientDownloader.kt:792)
	at com.intellij.remoteDev.downloader.CodeWithMeClientDownloader$MultipleSubProgressIndicator$Companion$create$element$1.invoke(CodeWithMeClientDownloader.kt:784)
	at com.intellij.remoteDev.downloader.CodeWithMeClientDownloader$MultipleSubProgressIndicator.setFraction(CodeWithMeClientDownloader.kt:805)
	at com.intellij.remoteDev.downloader.CodeWithMeClientDownloader$downloadClientAndJdk$5.run(CodeWithMeClientDownloader.kt:323)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-11-22 12:17:41,103 [1761688]   INFO - #c.g.c.j.g.c.e.CodespacesEnvComponent$ListCodespacesTask - refreshAvailableCodespaces was successful

```

**Description** 
Cannot connect to Codespaces, Visual Studio Code works without issue

**Steps to reproduce** 
Forked https://github.com/LinkedInLearning/level-up-php-249556/codespaces and added the ssh section, override the codespaces to use 4 CPU, open gateway, wait for a very long time for the download to complete (speedtest is 33 Mbps) then nothing happens.
**Impact** 
Cannot use software, Visual Studio code connects immediately.
**Additional context** 
OS: Windows 10
OS Version: 10.0
OS Architecture: amd64
Java Version: 17.0.5
Java Runtime Version: 17.0.5+7-b469.67
Java Vendor: JetBrains s.r.o.
Available CPUs: 12
Max Memory: 536870912
Free Memory: 35746608
Total Memory: 196083712
IDE Version: 2022.2.4
IDE: JetBrains Gateway 2022.2.4
Plugin Version: 0.2.0.930
Plugin path: C:\Users\100036751\AppData\Local\JetBrains\Toolbox\apps\Gateway\ch-0\222.4459.11.plugins\github-codespaces-gateway
Plugin ID: com.github.codespaces.jetbrains.gateway

```

**Comment by cmuto09** [comment] 2022-11-29 22:03
Hi @trevrobwhite! I'm having difficulty reproducing the issue- does this consistently fail for you or is it intermittent? Also when you go to connect to your Codespace, are you going to the Gateway directly, or are you linking through the GitHub website via the "Open in..." menu?

Thanks

**Comment by cmuto09** [comment] 2022-12-06 18:03
@trevrobwhite closing this as we are unable to reproduce. Please re-open if you run into it again, or get any more information. Thank you!

**Closed by cmuto09** 2022-12-06 18:03 UTC
