### ISSUE TITLE
GitHub Codespaces Feedback

### ISSUE THREAD

**Issue by mhrohani1385** [github/codespaces-jetbrains-feedback#24] opened 2022-11-15 10:31 UTC
**Description** 
**Steps to reproduce** 
**Impact** 
**Additional context** 
```
java.lang.Throwable: Could not get recovery container status: com.microsoft.tunnels.connections.TunnelConnectionException: Error verifying the ssh session.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.github.codespaces.jetbrains.observability.logging.GitHubLogger.error(GitHubLogger.kt:31)
	at com.github.codespaces.jetbrains.gateway.connector.CodespacesConnectorService$connect$1.run(CodespacesConnectorService.kt:97)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:425)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:509)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:177)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
OS Version: 5.15.0-52-generic
OS Architecture: amd64
IDE Version: 2022.3 Beta
Plugin Version: 0.3.0.898
Plugin path: /home/mhr-85/.local/share/JetBrains/JetBrainsGateway2022.3/github-codespaces-gateway
Plugin ID: com.github.codespaces.jetbrains.gateway

```

**Comment by shayneburgess** [comment] 2022-11-15 19:53
Closing as duplicate of https://github.com/github/codespaces-jetbrains-feedback/issues/16

**Closed by shayneburgess** 2022-11-15 19:53 UTC
Labels: tunnels

**Comment by cmuto09** [comment] 2022-11-29 23:09
Hey @mhrohani1385 - this issue is now resolved. You can follow the steps in #16 to update to a version of the plugin that includes this fix. Thanks!
