### ISSUE TITLE
GitHub Codespaces Feedback

### ISSUE THREAD

**Issue by AlexPl292** [github/codespaces-jetbrains-feedback#14] opened 2022-11-11 09:06 UTC
Hi, I had `gh` of version 2.12 installed on system and JetBrains client was throwing some exception instead of the suggestion to update `gh`.
Everything is okay since I updated `gh` to version 2.20 using brew

**Comment by shayneburgess** [comment] 2022-11-15 19:47
Closing as duplicate of https://github.com/github/codespaces-jetbrains-feedback/issues/17

**Closed by shayneburgess** 2022-11-15 19:47 UTC
Labels: cli, cli-version
